### ISSUE TITLE
How to execute a simple command?

### ISSUE THREAD

**Issue by andrejpavlovic** [fir3pho3nixx/grunt-spawn#8]
This is a command I would like to execute: `echo hello`. After half hour of playing with various options, I still don't know how to do it...

Here is what I tried:
```javascript
spawn: {
  echo: {
    command: 'echo',
    commandArgs: ['hello']
  }
}
```

The result is:
```cmd
c:\...>grunt spawn:echo
to: wrong arguments

toEnd: wrong arguments

Running "spawn:echo" (spawn) task


<grunt-spawn/>: Launching child process
>> <grunt-spawn/>: Launching 'echo hello' starting in 'C:\...' overridden with cwd='C:\...'
hello


<grunt-spawn/>: Launching child process
>> <grunt-spawn/>: Launching 'echo hello' starting in 'C:\...' overridden with cwd='C:\...'
hello
```

And it keeps on repeating into infinity. This is on Windows 8 if that makes a difference.

**Comment by fir3pho3nixx** [comment]
That is interesting, I have not tested this overly much on Windows. Would you mind trying to following sample I put together and let me know if this works for you? I tested on windows 10 and it seemed OK.

https://github.com/fir3pho3nixx/grunt-spawn/tree/master/diag

**Comment by andrejpavlovic** [comment]
It's working ok on Windows 8 as well. Adding `groupFiles: true` seems to fix the issue, because if I remove it, I get the endless loop again. I would never have guessed I would need to add this flag, but even if I don't, why would it cause an infinite loop when executing?

**Comment by fir3pho3nixx** [comment]
I think you are perceiving a endless loop because somehow grunt-spawn might be doing what I call "lame file scanning". An empty `pattern` property will default to a recursive '**/*.js'  and an empty `directory` property will default to the current folder '.\'. The infinite loop you are perceiving is perhaps every *.js file being scanned and found in something like the '.\node_modules' directory and then a failed command being executed for each individual file result. 

When setting `groupFiles` property to 'true', all we are saying is execute that same massive file scan/result as a single command.

For result = ['file1.txt', 'file2.txt', 'file3.txt']:

spawn:command file1.txt
spawn:command file2.txt
spawn:command file3.txt

Becomes:

spawn:command file1.txt file2.txt file3.txt

This is still wildly inefficient if you don't care about finding files and using them as an input to your grunt-spawn command. In these cases you can it off all together by setting the `passThrough` property to true. It bypasses file system scanning and does not use matched result as inputs to the grunt-spawn command.
 
I tried to explain this under the https://github.com/fir3pho3nixx/grunt-spawn#more-examples section of the README.md but perhaps you could recommend changes to make it more user friendly :)
